apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: am9rZXN1c2Vy
  POSTGRES_PASSWORD: ZW1hb3d1c3UxMjM=
  POSTGRES_DB: am9rZXNkYg==