apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  containers:
  - name: postgres
    image: evamecobblah/postgres:v1
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: jokesuser
    - name: POSTGRES_PASSWORD
      value: admin@223
    - name: POSTGRES_DB
      value: jokesdb
